title: Miniature Journey Blog
description: Experiments, progress logs, and runnable demos from each subproject.
baseurl: ""
url: "https://dommueller.github.io/miniature-journey"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
